<?xml version="1.0" encoding="utf-8"?>
<Data>
  <StatisticStartDate>2017-10-01</StatisticStartDate>
  <ResourceCategories>
    <ResourceCategory>
      <Name>Person</Name>
      <Color>-8388353</Color>
      <IsDefault>true</IsDefault>
    </ResourceCategory>
    <ResourceCategory>
      <Name>aaa</Name>
      <Color>-32704</Color>
      <IsDefault>false</IsDefault>
    </ResourceCategory>
    <ResourceCategory>
      <Name>bbb</Name>
      <Color>-65536</Color>
      <IsDefault>false</IsDefault>
    </ResourceCategory>
  </ResourceCategories>
  <Resources>
    <Resource>
      <Name>xxx</Name>
      <Notes></Notes>
      <Active>true</Active>
      <ResourceCategory>aaa</ResourceCategory>
      <StartDate>2017-10-27</StartDate>
    </Resource>
    <Resource>
      <Name>yyy</Name>
      <Notes></Notes>
      <Active>true</Active>
      <ResourceCategory>bbb</ResourceCategory>
      <StartDate>2017-10-27</StartDate>
    </Resource>
    <Resource>
      <Name>bb</Name>
      <Notes />
      <Active>true</Active>
      <ResourceCategory>Person</ResourceCategory>
      <StartDate>2017-10-27</StartDate>
    </Resource>
    <Resource>
      <Name>alex</Name>
      <Notes />
      <Active>true</Active>
      <ResourceCategory>Person</ResourceCategory>
      <StartDate>2017-10-27</StartDate>
    </Resource>
  </Resources>
  <Days>
    <Day>
      <Date>2017-10-30</Date>
      <Resource>bb</Resource>
    </Day>
    <Day>
      <Date>2017-10-31</Date>
      <Resource>alex</Resource>
    </Day>
    <Day>
      <Date>2017-11-01</Date>
      <Resource>alex</Resource>
    </Day>
    <Day>
      <Date>2017-11-02</Date>
      <Resource>bb</Resource>
    </Day>
    <Day>
      <Date>2017-11-03</Date>
      <Resource>alex</Resource>
    </Day>
    <Day>
      <Date>2017-11-06</Date>
      <Resource>yyy</Resource>
    </Day>
    <Day>
      <Date>2017-11-07</Date>
      <Resource>bb</Resource>
    </Day>
    <Day>
      <Date>2017-11-08</Date>
      <Resource>alex</Resource>
    </Day>
    <Day>
      <Date>2017-11-09</Date>
      <Resource>bb</Resource>
    </Day>
    <Day>
      <Date>2017-11-10</Date>
      <Resource>alex</Resource>
    </Day>
    <Day>
      <Date>2017-11-13</Date>
      <Resource>bb</Resource>
    </Day>
    <Day>
      <Date>2017-11-14</Date>
      <Resource>alex</Resource>
    </Day>
    <Day>
      <Date>2017-11-15</Date>
      <Resource>bb</Resource>
    </Day>
    <Day>
      <Date>2017-11-16</Date>
      <Resource>alex</Resource>
    </Day>
    <Day>
      <Date>2017-11-17</Date>
      <Resource>bb</Resource>
    </Day>
    <Day>
      <Date>2017-11-20</Date>
      <Resource>alex</Resource>
    </Day>
    <Day>
      <Date>2017-11-21</Date>
      <Resource>xxx</Resource>
    </Day>
    <Day>
      <Date>2017-11-22</Date>
      <Resource>bb</Resource>
    </Day>
    <Day>
      <Date>2017-11-23</Date>
      <Resource>alex</Resource>
    </Day>
    <Day>
      <Date>2017-11-24</Date>
      <Resource>bb</Resource>
    </Day>
    <Day>
      <Date>2017-11-27</Date>
      <Resource>yyy</Resource>
    </Day>
    <Day>
      <Date>2017-11-28</Date>
      <Resource>alex</Resource>
    </Day>
    <Day>
      <Date>2017-11-29</Date>
      <Resource>bb</Resource>
    </Day>
    <Day>
      <Date>2017-11-30</Date>
      <Resource>alex</Resource>
    </Day>
  </Days>
</Data>