<?xml version="1.0" encoding="utf-8"?>
<Data>
  <Resources>
    <Resource>
      <Name>AAC</Name>
      <Active>false</Active>
      <StartDate>2017-10-20</StartDate>
    </Resource>
    <Resource>
      <Name>BBB</Name>
      <Active>true</Active>
      <StartDate>2017-10-01</StartDate>
    </Resource>
    <Resource>
      <Name>CCC</Name>
      <Active>true</Active>
      <StartDate>2017-10-20</StartDate>
    </Resource>
    <Resource>
      <Name>DDD</Name>
      <Active>true</Active>
      <StartDate>2017-10-20</StartDate>
    </Resource>
    <Resource>
      <Name>EEE</Name>
      <Active>true</Active>
      <StartDate>2017-10-20</StartDate>
    </Resource>
    <Resource>
      <Name>FFF</Name>
      <Active>false</Active>
      <StartDate>2017-10-20</StartDate>
    </Resource>
    <Resource>
      <Name>GGG</Name>
      <Active>true</Active>
      <StartDate>2017-10-20</StartDate>
    </Resource>
    <Resource>
      <Name>HHH</Name>
      <Active>true</Active>
      <StartDate>2017-10-20</StartDate>
    </Resource>
    <Resource>
      <Name>III</Name>
      <Active>true</Active>
      <StartDate>2017-10-20</StartDate>
    </Resource>
    <Resource>
      <Name>JJJ</Name>
      <Active>true</Active>
      <StartDate>2017-10-20</StartDate>
    </Resource>
    <Resource>
      <Name>KKK</Name>
      <Active>true</Active>
      <StartDate>2017-10-20</StartDate>
    </Resource>
  </Resources>
  <Days>
    <Day>
      <Date>2017-10-02</Date>
      <Resource>AAC</Resource>
    </Day>
    <Day>
      <Date>2017-10-21</Date>
      <Resource>BBB</Resource>
      <Resource>AAC</Resource>
    </Day>
    <Day>
      <Date>2017-10-22</Date>
      <Resource>CCC</Resource>
    </Day>
    <Day>
      <Date>2017-10-23</Date>
      <Resource>DDD</Resource>
    </Day>
    <Day>
      <Date>2017-10-24</Date>
      <Resource>EEE</Resource>
      <Resource>AAC</Resource>
    </Day>
    <Day>
      <Date>2017-10-25</Date>
      <Resource>FFF</Resource>
    </Day>
    <Day>
      <Date>2017-10-26</Date>
      <Resource>GGG</Resource>
    </Day>
    <Day>
      <Date>2017-10-27</Date>
      <Resource>HHH</Resource>
    </Day>
    <Day>
      <Date>2017-10-28</Date>
      <Resource>III</Resource>
    </Day>
    <Day>
      <Date>2017-10-29</Date>
      <Resource>JJJ</Resource>
    </Day>
    <Day>
      <Date>2017-10-30</Date>
      <Resource>KKK</Resource>
    </Day>
    <Day>
      <Date>2017-10-01</Date>
      <Resource>AAC</Resource>
      <Resource>GGG</Resource>
    </Day>
    <Day>
      <Date>2017-10-03</Date>
      <Resource>FFF</Resource>
    </Day>
    <Day>
      <Date>2017-10-04</Date>
      <Resource>HHH</Resource>
    </Day>
    <Day>
      <Date>2017-10-05</Date>
      <Resource>HHH</Resource>
    </Day>
    <Day>
      <Date>2017-10-06</Date>
      <Resource>BBB</Resource>
    </Day>
    <Day>
      <Date>2017-10-07</Date>
      <Resource>JJJ</Resource>
    </Day>
    <Day>
      <Date>2017-10-08</Date>
      <Resource>KKK</Resource>
    </Day>
    <Day>
      <Date>2017-11-01</Date>
      <Resource>AAC</Resource>
    </Day>
    <Day>
      <Date>2017-11-02</Date>
      <Resource>BBB</Resource>
    </Day>
    <Day>
      <Date>2017-11-03</Date>
      <Resource>CCC</Resource>
    </Day>
    <Day>
      <Date>2017-10-15</Date>
      <Resource>GGG</Resource>
    </Day>
    <Day>
      <Date>2017-10-16</Date>
      <Resource>GGG</Resource>
    </Day>
    <Day>
      <Date>2017-10-31</Date>
      <Resource>GGG</Resource>
    </Day>
    <Day>
      <Date>2017-10-11</Date>
      <Resource>DDD</Resource>
    </Day>
    <Day>
      <Date>2017-10-09</Date>
      <Resource>AAC</Resource>
    </Day>
    <Day>
      <Date>2017-10-10</Date>
      <Resource>AAC</Resource>
    </Day>
  </Days>
</Data>